### ISSUE TITLE
Hello, I want to know what algorithm this is based on, is it model training or chroma key

### ISSUE THREAD

**Issue by zhanghongyong123456** [prithviie/green-screen#1]
Hello, I want to know what algorithm this is based on, is it model training or chroma key

**Comment by prtvi** [comment]
Hello there, the program is basically checking every pixel in the foreground image for the intensity of the green color. If the intensity of the green color is beyond a certain threshold, that pixel is replaced with a pixel from the background image.
You can get a detailed explanation here - https://prtvi.github.io/html/projects/greenScreen.html
